language: python

python:
  - "3.6.9"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

install:
  - pip install -r requirements.txt
  - pip install djangorestframework_simplejwt

script:
  - coverage run --source=api manage.py test && coverage report 

after_success:
- coveralls